### ISSUE TITLE
Activity 1: What branches to compare in pull request

### ISSUE THREAD

**Issue by mfaerevaag** [KAIST-IS521/2017-Spring#1]
Hello,

The [last item](https://github.com/KAIST-IS521/2017-Spring/blob/master/activities/0306-git.tex#L94-L97) in in Activity 1 asks the student to create a pull request. Unfortunately I am not sure exactly what is expected:
 - What should the pull request be about or what branches should be compared? 
 - And are we still talking about the student's private repo, or [this repo](https://github.com/KAIST-IS521/2017-Spring)?

Thank you very much,
Markus

**Comment by mfaerevaag** [comment]
Sorry, I do not have permissions to add the `question` label to the issue.

**Comment by sangkilc** [comment]
Markus,

Thanks for pointing this out. I didn't link with any base repository when I created this assignment, and as a result, you don't see any branch to compare with.

I modified the assignment, but in order to apply this change, your private repository needs to be deleted, and then re-created. For this assignment, you can ignore opening a pull request.

For the labeling issue, we (course staffs) will label issues, and the document is fixed accordingly: see 89873160fef9bc2447c14d14b1362b619962112f.

**Comment by sangkilc** [comment]
Actually, let me clarify the previous answer. According to this [link](https://github.com/education/classroom/issues/333), students cannot open a pull request if student's repository is created with github classroom. I will explain this further in the next lecture. Thanks again for pointing this out 👍

**Comment by mfaerevaag** [comment]
Alright, that makes sense. Thank you!
