### ISSUE TITLE
Question for worm activity

### ISSUE THREAD

**Issue by dinggul** [KAIST-IS521/2017-Spring#72]
At step 5 in 3.1,

> It re-connects to the server with the obtained user name and the password from Step 3. If the login works, it records the IP address of the vulnerable host along with a user name and a password. Otherwise, it simply records the IP address with a user name “superuser”.

I cannot understand meaning of "Otherwise".
As I think, If I can login with 'superuser', I can get correct a pair of id/pw always.
So I can guess there is no possibility for "Otherwise".

Am I misunderstanding?
I would like to know more precise condition to record "superuser" for certain IP address.

**Comment by sangkilc** [comment]
> As I think, If I can login with 'superuser', I can get correct a pair of id/pw always.

This is simply to make the description more general, because there is no perfect way for a program to decide whether you are logged in or not. So if for whatever reason your program is not sure whether it is logged in or not, then you may want to record "superuser". It is okay to not consider this corner case.
