### ISSUE TITLE
worms in the zip.gpg file

### ISSUE THREAD

**Issue by mickan921** [KAIST-IS521/2017-Spring#80]
I noticed that my worm (mickan921) is not present among the worms given.

Were the worms randomly selected? or should I be worried?

thanks

**Comment by sangkilc** [comment]
Your worm doesn't compile on the VM that we provided. TAs (@seungsoo-lee @jae519 ) will be able to answer your question.

**Comment by seungsoo-lee** [comment]
Hi, 

The problem seems that the difference in GCC version between your Linux environment and the provided VM (is521.box). As I know, the professor said that the standard is the provided VM although you can use your own VM machine.

Anyway, we will re-build your worm but, also deduct the grade little bit.

Thanks

**Comment by soomin-kim** [comment]
We updated binary. Could you please check again?

Thanks.

**Comment by mickan921** [comment]
It's still not there...

Do you want me to push the fixed version?

**Comment by sangkilc** [comment]
Updated again.
