### ISSUE TITLE
[av activity] What should our scanners do exactly?

### ISSUE THREAD

**Issue by dinggul** [KAIST-IS521/2017-Spring#81]
If there is a 'myworm' malware that has slightly different semantics (such as not scanning given ip range),

should our scanners filter it? or not?

**Comment by sangkilc** [comment]
As an AV provider, will you detect such variants as malicious or not? The answer may depend on what you mean by dummy data, but it makes sense to me to consider it as malicious, because spreading garbage data is bad in general. Think about adware we discussed in the class.

Notice, this assignment is really open-ended.

**Comment by dinggul** [comment]
In general, I agree with you answered.
But I slightly confused because of these sentence at activity overview:

> Since the malware samples (although it is written by different authors) have the same semantics, and we can call them as the “myworm” malware family.

> (1) design a scanner that detects the “myworm“ malware family using a library called YARA

So I still feel hard to set the range of "myworm" family.
Since this border line is also used at making variant sample and benign sample, this is really important as I think.

**Comment by sangkilc** [comment]
I would define myworm family as follows: if a program scans network ports to find vulnerable vulnet services, and if the program exploits the backdoor vulnerability of vulnet to perform an arbitrary action, then the program is malicious, and it is a member of the myworm family.

**Comment by dinggul** [comment]
Thank you. That would be really helpful.
